# Generated by Django 2.1.4 on 2019-01-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='level',
        ),
        migrations.AddField(
            model_name='lesson',
            name='code',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
