# Generated by Django 2.1.4 on 2019-02-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_auto_20190218_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='lessons',
        ),
        migrations.AddField(
            model_name='topic',
            name='colour',
            field=models.CharField(choices=[('1', 'brand'), ('2', 'accent-2'), ('3', 'accent-3'), ('4', 'accent-4')], default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='topic',
            name='difficulty',
            field=models.IntegerField(default=0),
        ),
    ]
