# Generated by Django 2.1.4 on 2019-03-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_auto_20190218_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='favourite_lessons',
            new_name='completed_lessons',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_registered',
        ),
        migrations.RemoveField(
            model_name='student',
            name='level',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AddField(
            model_name='student',
            name='completed_topics',
            field=models.ManyToManyField(to='lessons.Topic'),
        ),
        migrations.AddField(
            model_name='student',
            name='uid',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
