# Generated by Django 2.1.4 on 2019-03-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_auto_20190303_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image_url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='student',
            name='completed_lessons',
            field=models.ManyToManyField(blank=True, to='lessons.Lesson'),
        ),
        migrations.AlterField(
            model_name='student',
            name='completed_topics',
            field=models.ManyToManyField(blank=True, to='lessons.Topic'),
        ),
    ]
