# Generated by Django 2.1.4 on 2019-03-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_auto_20190307_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
